server:
  port: 9098
  servlet:
    context-path: /api
spring:
  application:
    ###服务的名称
    name: edu
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eduDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
logging:
  level:
    ###打印mybatis日志
    com.zz.mapper: debug

zz:
  userName: zz
  thread:
    corePoolSize: 8 # 一直正在运行线程数 2  IO相关 cpu核数*2 cpu相
    maxPoolSize: 8
    queueCapacity: 1000
    keepAlive: 60