server:
  port: 9098
spring:
  application:
    ###服务的名称
    name: edu
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eduDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
logging:
  level:
    ###打印mybatis日志
    com.zz.mapper: debug